### ISSUE TITLE
Using Vue Cli, import windi.css fails

### ISSUE THREAD

**Issue by joseluisgs** [windicss/vue-cli-plugin-windicss#26]
Hi
I start a project using Vue CLI with Vue3 and TS
I use vue add windicss   
In my main.ts I have import 'windi.css';

But I have the following problem

 Unable to resolve path to module 'windi.css'  import/no-unresolved
@ multi (webpack)-dev-server/client?http://192.168.1.47:8081&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

Any ideas to solve it?

**Comment by harlan-zw** [comment]
Hey @joseluisgs 

Looks like this is an issue from eslint, specifically the [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) plugin. Because the windi module provided is a virtual module, it means it doesn't exist within your file system.

I'm not too across this plugin but you can probably resolve the issue by specifying windi as a core module https://github.com/import-js/eslint-plugin-import/blob/main/README.md#importcore-modules.

Otherwise, you could just ignore the import line

**Comment by martiliones** [comment]
Adding to `.eslintrc.js` the following code works for me:
```js
module.exports = {
  settings: {
    'import/core-modules': [ 'windi.css' ]
  }
}
```

**Comment by harlan-zw** [comment]
Thanks @martiliones! 

Will close this off for now as that solution should resolve it.

**Comment by joseluisgs** [comment]
Thank you very much!!

**Comment by ymjrcc** [comment]
> Adding to `.eslintrc.js` the following code works for me:
> 
> ```js
> module.exports = {
>   settings: {
>     'import/core-modules': [ 'windi.css' ]
>   }
> }
> ```

Thank you ！！！！！！！！！！
